"""empty message

Revision ID: 9f90ab232821
Revises: cb39a28d4c12
Create Date: 2020-12-02 21:55:35.958274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f90ab232821'
down_revision = 'cb39a28d4c12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('register', 'password',
               existing_type=sa.VARCHAR(length=35),
               type_=sa.String(length=200),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('register', 'password',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=35),
               existing_nullable=False)
    # ### end Alembic commands ###
