"""empty message

Revision ID: cb39a28d4c12
Revises: 
Create Date: 2020-12-02 21:08:02.418188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb39a28d4c12'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('register', sa.Column('FirstName', sa.String(length=50), nullable=True))
    op.add_column('register', sa.Column('LastName', sa.String(length=50), nullable=True))
    op.add_column('register', sa.Column('mobile', sa.String(length=15), nullable=True))
    op.alter_column('register', 'password',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.drop_constraint('register_number_key', 'register', type_='unique')
    op.create_unique_constraint(None, 'register', ['mobile'])
    op.drop_column('register', 'number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('register', sa.Column('number', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'register', type_='unique')
    op.create_unique_constraint('register_number_key', 'register', ['number'])
    op.alter_column('register', 'password',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.drop_column('register', 'mobile')
    op.drop_column('register', 'LastName')
    op.drop_column('register', 'FirstName')
    # ### end Alembic commands ###
